### ISSUE TITLE
Can't seem to use this

### ISSUE THREAD

**Issue by Travistyse** [seep/JoltPhysicsUnity#1]
There isn't a package for Unity to find and it isn't a project that can be loaded via Unity Hub so I added it into my project manually inside of a folder named Jolt. I'm using the current latest version of the LTS (2022.3.21f1) and the scenes are just unshaded (no materials exist for them) and don't move or anything. The stack of cubes just remain static, for instance.

I'm highly interested in using Jolt, the only errors that I'm seeing are:

DllNotFoundException: joltc assembly:<unknown assembly> type:<unknown type> member:(null)
Jolt.JoltAPI..cctor () (at Assets/Jolt/Jolt/JoltAPI.cs:56)
Rethrow as TypeInitializationException: The type initializer for 'Jolt.JoltAPI' threw an exception.
Jolt.PhysicsSystem.Step (System.Single deltaTime, System.Int32 collisionSteps, Jolt.PhysicsUpdateError& error) (at Assets/Jolt/Jolt/Physics/PhysicsSystem.cs:43)
Jolt.Samples.PhysicsController.FixedUpdate () (at Assets/Jolt/Jolt.Samples/Scripts/PhysicsController.cs:42)

and

DllNotFoundException: joltc assembly:<unknown assembly> type:<unknown type> member:(null)
Jolt.JoltAPI..cctor () (at Assets/Jolt/Jolt/JoltAPI.cs:56)
Rethrow as TypeInitializationException: The type initializer for 'Jolt.JoltAPI' threw an exception.
Jolt.PhysicsSystem..ctor (Jolt.PhysicsSystemSettings settings) (at Assets/Jolt/Jolt/Physics/PhysicsSystem.cs:19)
Jolt.Samples.PhysicsController.Start () (at Assets/Jolt/Jolt.Samples/Scripts/PhysicsController.cs:28)

And probably others that all amount to the same thing - I've clearly not added these files the way that they were meant to be.

**Comment by seep** [comment]
The package isn't published on any registries right now. You can 

1. [Include it as a git package](https://docs.unity3d.com/Manual/upm-ui-giturl.html)

2. [Embed it in your Packages folder](https://docs.unity3d.com/Manual/upm-embed.html)

You were close to embedding it, just move the package contents from the `Assets` folder to a subdirectory in the `Packages` folder.

The broken materials might be because your project is using URP. The sample scenes are configured to use the Built-In Renderer Pipeline.
